# Set the base image to Ubuntu
FROM ubuntu

# File Author / Maintainer
MAINTAINER Example McAuthor

# Executed during the Provisiong
RUN echo "Docker Provisioned: Hello docker!"

# Executed during RUN of the Docker Instance
CMD echo "Docker Running!! Hello WORLD"