# Set the base image to Ubuntu
FROM ubuntu

# File Author / Maintainer
MAINTAINER Example McAuthor

# During the Provisiong
RUN echo "Docker Provisioned: Hello docker!"

# During RUN of the Docker Instance
CMD echo "Docker Running!! Hello WORLD"